### this is a line break
# we can define variables to use in the rest query
@newlyPostedEmployeeId=1a513ea6-5655-4665-6adf-08db2b2274c2
@baseUri=https://localhost:7165/api/companies
@testEmployees={{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees
@root=https://localhost:7165/api/
@testCompany=https://localhost:7165/api/companies/3d490a70-94ce-4d15-9494-5248280c2ce3

# get all employees
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=3&pageSize=3
###
POST {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/
Content-Type: application/json

{
"name":"new rest tool",
"age":"19",
"position":"chaylak"

}
###
PUT {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
Content-Type: application/json

{
"name":"updated new test tool",
"age":"20",
"position":"chaylak"
}

###
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
###
# recheck patch newtonjson etc..
PATCH {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
Content-Type:application/json

{
"age":"18"
}
### search term added 
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=2&pageSize=2&searchTerm=m

### orderby added
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=3&pageSize=2&searchTerm=m&orderBy=name,age desc

### datashaping.. only positions data is requested !!
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?fields=position

### her bringer opp uventede properties og.
GET {{testEmployees}}/pageNumber=2&pageSize=3&minAge=26&maxAge=34&searchTerm=A&orderBy=name desc&fields=name,position

### able to get options in header 
OPTIONS {{baseUri}}

### GETS HEAD RESPONSE AS 1 AND HEADER PAGINATION AS EXPECTED
HEAD {{testEmployees}}

### root document (type validation check needs skipped for postman to function)
GET {{root}}
Accept:application/application/vnd.codemaze.apiroot+json

### versioning by query string -- gets controller v2 
GET {{baseUri}}?api-version=2.0

### versioning by url -- gets controller v2
GET {{root}}2.0/companies

#### versioning by http header 
GET {{baseUri}}
api-version:2.0

### response cashe attribute test-- Cache-Control: public, max-age=60
GET {{testCompany}}
# Cache-Control header was created with a public cache and a duration of 60 seconds. But as we said, this is just a header; we need a cache-store to cache the response.

### cashing test 
GET {{baseUri}}
# We can see that we have all the required headers generated. The default expiration is set to 60 seconds and if we send this request one more time, we are going to get an additional Age header.
# cashe control, etag, expires, last modified, transfer encoding, vary

### cashing test 
GET {{testCompany}}

### cashing test 
GET {{testEmployees}}

### cash expiration&validation test-done as well

### ratelimit and throttling test
GET {{baseUri}}
# Status code: 429 (429) -- Retry-After: 119 -- API calls quota exceeded! maximum admitted 3 per 5m.

### authentication --> user, roles, passwords initiated.. 
POST {{root}}/authentication
{
"firstname":"david",
"lastname":"saga",
"username":"davids",
"password":"passme1nn1",
"email":"testinginn@testing.com",
"phonenumber":"123-987",
"roles":["Manager"]
}
### registration in postman succeeded
POST https://localhost:7165/api/authentication
{
"firstname":"david2",
"lastname":"saga2",
"username":"davids2",
"password":"passme1nn12",
"email":"testinginn2@testing.com",
"phonenumber":"123-982",
"roles":["Manager"]
}
# 201 created
# works fine in postman.. just dont know how to send here, yet

### login failed 
POST https://localhost:7165/api/authentication/login
{
"username":"davids2",
"password":"passme1nn12"
}
# problem solved.. SECRETKEY --> EnvirKey
# {
#    "StatusCode": 500,
#    "Message": "String reference not set to an instance of a String. (Parameter 's')"
#}
#
#{
#    "StatusCode": 500,
# "Message": "IDX10653: The encryption algorithm 'HS256' requires a key size of at least '128' bits. 
# Key '[PII of type 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey' is hidden. 
# For more details, see https://aka.ms/IdentityModel/PII.]', is of size: '64'. (Parameter 'key')"
#}

