### this is a line break
# we can define variables to use in the rest query
@newlyPostedEmployeeId=1a513ea6-5655-4665-6adf-08db2b2274c2
@baseUri=https://localhost:7165/api/companies
@testEmployee={{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees
@root=https://localhost:7165/api/

# get all employees
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=3&pageSize=3
###
POST {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/
Content-Type: application/json

{
"name":"new rest tool",
"age":"19",
"position":"chaylak"

}
###
PUT {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
Content-Type: application/json

{
"name":"updated new test tool",
"age":"20",
"position":"chaylak"
}

###
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
###
# recheck patch newtonjson etc..
PATCH {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees/{{newlyPostedEmployeeId}}
Content-Type:application/json

{
"age":"18"
}
### search term added 
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=2&pageSize=2&searchTerm=m

### orderby added
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?pageNumber=3&pageSize=2&searchTerm=m&orderBy=name,age desc

### datashaping.. only positions data is requested !!
GET {{baseUri}}/3d490a70-94ce-4d15-9494-5248280c2ce3/employees?fields=position

### her bringer opp uventede properties og.
GET {{testEmployee}}/pageNumber=2&pageSize=3&minAge=26&maxAge=34&searchTerm=A&orderBy=name desc&fields=name,position

### able to get options in header 
OPTIONS {{baseUri}}

### GETS HEAD RESPONSE AS 1 AND HEADER PAGINATION AS EXPECTED
HEAD {{testEmployee}}

### root document (type validation check needs skipped for postman to function)
GET {{root}}
Accept:application/application/vnd.codemaze.apiroot+json

### versioning by query string -- gets controller v2 
GET {{baseUri}}?api-version=2.0

### versioning by url -- gets controller v2
GET {{root}}/2.0/companies

